### ISSUE TITLE
Bssid = null since update to Catalina 10.15.4

### ISSUE THREAD

**Issue by HelgeKeck** [xamarin/mac-samples#129]
The used code from the example:

HelloCoreWlanSample.cs 

doesnt work anymore as expected. Dont know if it is a bug or a new restriction, but the system always returns NULL for the Bssid value.

**Comment by chamons** [comment]
This appears to be an Apple change: https://forums.developer.apple.com/thread/124189

I'm going to leave it open, as if there are ways to fix the sample I'm all ears.

**Comment by mjtpena** [comment]
You need to request for location access for it to work. 


using CoreLocation;

            var manager = new CLLocationManager();
            manager.RequestAlwaysAuthorization();

**Comment by HelgeKeck** [comment]
👍

**Comment by mjtpena** [comment]
Created a PR:

https://github.com/xamarin/mac-samples/pull/139
