### ISSUE TITLE
NSScrollExample (Xamarin documentation) does not work

### ISSUE THREAD

**Issue by GT85** [xamarin/mac-samples#130]
MacOS Mojave 10.14.6 dark mode, VS for Mac Community 8.5.4

Hello.
Running this app displays a small black window (500 x 250 ?) with 2 buttons and no scroll bars. Extending this window add gray surface up and right.
Could you please fix this bug or explain my error ?
Regards,
Gilbert

<img width="650" alt="Capture d’écran 2020-04-29 à 14 35 35" src="https://user-images.githubusercontent.com/33017626/80596490-bc412e00-8a26-11ea-8ec5-f047e3f70484.png">

**Comment by chamons** [comment]
This is what i see:

![Screen Shot 2020-04-29 at 3 12 12 PM](https://user-images.githubusercontent.com/6392201/80642288-d5001280-8a2b-11ea-8e93-d30cb334affe.png)

If you move the mouse over the lower left, you should see the scroll view.

**Comment by chamons** [comment]
Depending on your setting here:

![image](https://user-images.githubusercontent.com/6392201/80642357-f660fe80-8a2b-11ea-98b9-e973345eafa3.png)

In System Settings -> General you may see different SO default draws.

**Comment by GT85** [comment]
Hi Chris.
OK. That works with 2 fingers on the trackpad. Also with the mouse if I set "Always".
Thanks,
Gilbert
