### ISSUE TITLE
DragAndDropExample Crashes on MacOS

### ISSUE THREAD

**Issue by robloo** [xamarin/mac-samples#135]
The Drag and Drop example application is non-functional on MacOS.

1. Run the app
2. Click in the left/red source rectangle -> will crash

Is there a known work-around for this?

**Comment by rolfbjarne** [comment]
Here's the fix: https://github.com/xamarin/mac-samples/pull/136/files, that PR should be merged later today.

**Comment by robloo** [comment]
Thanks for looking at this so quickly! It was difficult for me to understand where the problem was coming from and how to fix it.
