### ISSUE TITLE
Samples like ProductTable don't implement cell reuse

### ISSUE THREAD

**Issue by rmarinho** [xamarin/mac-samples#14]
If you increase the number of rows in the products sample, you will see new cell won't be update. 

We need to update the code to update a reused cell.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
