### ISSUE TITLE
Can you add an example of how to load and display an SVG image?

### ISSUE THREAD

**Issue by Emasoft** [xamarin/mac-samples#2]
Can you add an example of how to load and display an SVG image? Thank you.

**Comment by Rajneesh360Logica** [comment]
Hi @Emasoft 
Thanks for reporting the issue. I have filed a for the same in bugzilla.

https://bugzilla.xamarin.com/show_bug.cgi?id=42157

Thanks..!

**Comment by olegoid** [comment]
Please continue any discussions on this issue in Bugzilla.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
