### ISSUE TITLE
Animations example is not working

### ISSUE THREAD

**Issue by danipen** [xamarin/mac-samples#31]
Hi,

I'm trying to implement a custom animation based on the following example: https://github.com/xamarin/mac-samples/tree/master/CoreAnimationBook/CustomizeAnimation

I'm trying that example with Visual Studio for Mac 7.2 (Xamarin.Mac version: 3.8.0.49) and the example seems not to work. The line width is not animated. FYI, the method `MyView::DefaultAnimationFor` is never called.

Could you please help there?

**Comment by rolfbjarne** [comment]
This seems to work fine for me, the line width animates when I let go of the slider (and a breakpoint in the `DefaultAnimatorFor` method is also hit at the same time).

I'm closing this for now, but feel free to reopen if you can still reproduce after updating to the latest of Xamarin.Mac.
