### ISSUE TITLE
How can I resolve dependency of OpenTK.dll?

### ISSUE THREAD

**Issue by drunkhacker** [xamarin/mac-samples#4]
I cloned this repository and try to build OpenGLViewSample project, but with no success.
Xamarin complained it can't find OpenTK, so I edited references through "edit references" menu, added "OpenTK.dll". I built OpenTK.dll by downloading & compile sources from http://sourceforge.net/projects/opentk/?source=typ_redirect which is last version I think. (2014-07-23)

Now it keeps complaining about ambiguity between 
"using OpenGL" and "using OpenTK.Graphics.OpenGL".

By commenting out "opentk.grpahics.opengl", it runs but I think this isn't what you guys intended when you upload samples. 

Can you guide me how to build sample project using OpenTK? Which version of OpenTK should I use?

Any help will be appreciated. Thanks.

PS: Attached screenshot is depicts build error due to ambiguity I mentioned.
![2015-01-27 9 55 24](https://cloud.githubusercontent.com/assets/461823/5918762/a51553dc-a66f-11e4-9656-8096548e4460.png)

**Comment by Rajneesh360Logica** [comment]
Hi @drunkhacker, thanks for reporting this issue. Now we are no longer able to reproduce this issue. We are able to build and run XM OpenGLViewSample successfully without any error.

Screencast: http://www.screencast.com/t/fkSST7vw

So as of now I am closing this issue. Please let me know if am missing something.

Thanks..!
