### ISSUE TITLE
CoreWLANWirelessManager should gracefully exit if no WiFi interface is available on host

### ISSUE THREAD

**Issue by manish** [xamarin/mac-samples#50]
When there is no WiFi interface present on the host, `interfacesPicker.AddItems(CWInterface.InterfaceNames)` throws `System.ArgumentNullException` as `CWInterface.InterfaceNames`.

This is not the best experience for a sample and we need to gracefully exit with an error message.

Screenshot:

![No WiFi interfaces present exception](http://xqa.blob.core.windows.net/gist/021-No-Top-Stack.png-9d892d9c9aa54c949a51672076812331.png)

**Comment by bradumbaugh** [comment]
Thanks @manish. Apologies for the slow response; this was fixed with https://github.com/xamarin/mac-samples/pull/86.
