### ISSUE TITLE
Xamarin for Mac compiles F# code but not correctly and it outputs "read: -p: no corprocess" error to terminal

### ISSUE THREAD

**Issue by jacqueline-homan** [xamarin/mac-samples#6]
I have tried uninstalling and reinstalling the Xamarin for Mac several times and used the source listed for the Xamarin for Mac tool listed on the F# foundation web page.
![xamarin4mac](https://cloud.githubusercontent.com/assets/3537889/9289604/a7dfca9e-4344-11e5-9394-f753a7888e54.png)
![xamarinformac2](https://cloud.githubusercontent.com/assets/3537889/9289605/ada7a49c-4344-11e5-976e-ae985d6c4b65.png)

**Comment by jacqueline-homan** [comment]
![xamarin4mac2](https://cloud.githubusercontent.com/assets/3537889/9289946/94577a72-434d-11e5-9596-0db97828318e.png)

**Comment by Rajneesh360Logica** [comment]
Hi @jacqueline-homan, thanks for reporting this issue. Now I we are no longer able to reproduce this issue. We are able to build the XM F# temaplate project using terminal and as well in Xamarin studio.

Build Output: https://gist.github.com/Rajneesh360Logica/10fb28757712d386bbb1992726f39191

So as of now I am closing this issue. Please  let us know if we are missing something.

Thanks..!
