### ISSUE TITLE
Copy many dylibs to bundle

### ISSUE THREAD

**Issue by mfkl** [xamarin/mac-samples#89]
Hi,

Thanks for this repo, it's been helpful.

I have a question regarding this example: https://github.com/xamarin/mac-samples/tree/master/UseMSBuildToCopyFilesToBundleExample

I'm writing a targets file for a nuget package, to attempt to bundle several dylibs. https://github.com/mfkl/libvlc-nuget/pull/5

Could you please share a way to iterate over files using that Target when trying to bundle many files?

Appreciate the advice.

**Comment by bradumbaugh** [comment]
Hi @mfkl, thanks for the question, but this repository is only intended for questions directly related to the samples. For support with specific questions like this, take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!
