### ISSUE TITLE
MacCopyPast Error : must implement new interface

### ISSUE THREAD

**Issue by Gespix** [xamarin/mac-samples#93]
Hello,

I had an error with the MacCopyPast project : the interface `NSSecureCoding` must be implemented on `ImageInfo` for Copy/Past operations.

You juste have to : 
- Add `INSSecureCoding` to the class declaration
- Add this property 
`
[Export("supportsSecureCoding")]
public static bool SupportsSecureCoding => true;
`
Et voilà ;-)

**Comment by bradumbaugh** [comment]
Thanks for reporting, @Gespix. I put together a [PR](https://github.com/xamarin/mac-samples/pull/94) with your suggested change, so we'll get that reviewed and merged. Appreciate the help with the fix!
