### ISSUE TITLE
Hook into events/behaviors/lifecycle in the SourceWriter Sample.

### ISSUE THREAD

**Issue by sirfarmalot** [xamarin/mac-samples#95]
Thank you for this repository of work.

I would like to upon save, save that text string into the cloud.

Is there anyway to hook into the save method?

Thanks

**Comment by bradumbaugh** [comment]
Hi @sirfarmalot, glad this repository is helpful for you.

Take a look at the `SaveDocument` method in **EditorWindowController.cs**. This method is called when the document is saved.
